// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqYh7W5-ftOjhczwZrqHFmxt3EA3l5VCU',
    appId: '1:479516932795:web:1f1f2ba0789efddc70079e',
    messagingSenderId: '479516932795',
    projectId: 'zen-home-24d21',
    authDomain: 'zen-home-24d21.firebaseapp.com',
    storageBucket: 'zen-home-24d21.firebasestorage.app',
    measurementId: 'G-PYB6YSY0J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCfVGTHvxY8zL91pF6BqaNevfeZYl-ts',
    appId: '1:479516932795:android:7d42c601930da82a70079e',
    messagingSenderId: '479516932795',
    projectId: 'zen-home-24d21',
    storageBucket: 'zen-home-24d21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnjj073oT7Zmw96Y6gb_j-WywI_80hvbs',
    appId: '1:479516932795:ios:6144f294c0059ba870079e',
    messagingSenderId: '479516932795',
    projectId: 'zen-home-24d21',
    storageBucket: 'zen-home-24d21.firebasestorage.app',
    iosBundleId: 'com.zenhome.spa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnjj073oT7Zmw96Y6gb_j-WywI_80hvbs',
    appId: '1:479516932795:ios:71e6be80901de60270079e',
    messagingSenderId: '479516932795',
    projectId: 'zen-home-24d21',
    storageBucket: 'zen-home-24d21.firebasestorage.app',
    iosBundleId: 'com.example.widgetHomeDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqYh7W5-ftOjhczwZrqHFmxt3EA3l5VCU',
    appId: '1:479516932795:web:38f530384ff712ee70079e',
    messagingSenderId: '479516932795',
    projectId: 'zen-home-24d21',
    authDomain: 'zen-home-24d21.firebaseapp.com',
    storageBucket: 'zen-home-24d21.firebasestorage.app',
    measurementId: 'G-H1W6VXZCDW',
  );
}
